### ISSUE TITLE
jflex-maven-plugin 1.9.0/1 are missing from maven central

### ISSUE THREAD

**Issue by yonatang** [jflex-de/jflex#1081]
https://search.maven.org/artifact/de.jflex/jflex
![image](https://user-images.githubusercontent.com/697449/225447243-fa28ac79-94a8-491c-85e7-6b80d6cbd00c.png)

**Comment by lsf37** [comment]
It does appear for me here: https://central.sonatype.com/search?smo=true&q=jflex-maven-plugin (Latest version: 1.9.1) and https://mvnrepository.com/artifact/de.jflex/jflex also shows 1.9.1.
