### ISSUE TITLE
Não consigo executar o meu ficheiro.flex no cmd

### ISSUE THREAD

**Issue by EdsonVaz2020** [jflex-de/jflex#1101]
Esta dando este erro: Microsoft Windows [versão 10.0.16299.1127] (c) 2017 Microsoft Corporation.  Todos os direitos reservados.

 C:\ProjetoCompilador>jflex arquivo.flex Lendo "ficheiro.flex"

 Construindo ANF:

 Exceção inesperada encontrada.  Isso indica um bug no JFlex.  Considere registrar um problema em http://github.com/jflex-de/jflex/issues/new

 SERVEIndex 47 fora dos limites para comprimento 47 java.lang.IndexOutOfBoundsException: Índice 47 fora dos limites para comprimento 47

 em java.base/jdk.internal.util.Preconditions.outOfBounds (Preconditions.java:100) em java.base/jdk.internal util.  Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)

 em java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)

 em java.base/java.util.Objects.checkIndex(Objects.java:385) em java.base/java.util.ArrayList.get(ArrayList.java:427)

 em jflex.core.unicode.CharClasses.getClassCode (CharClasses.java:191) em jflex.core.  NFA.insertStringNFA (NFA.java:544)

 em jflex.core.  NFA.insertNFA (NFA.java:912)

 em jflex.core.NFA.addRegExp(NFA.java:187)

 em jflex.core.LexParse$CUP$LexParse$actions.CUP$LexParse$do_action_parte0000000(LexParse.java:105 em jflex.core.LexParse$CUP$LexParse$actions.CUP$LexParse$do_action(LexParse.java:2257)

 em jflex.core.LexParse.do_action(LexParse.java:598)

 em java_cup.runtime.1r_parser.parse(1r_parser.java:699) em jflex.generator.  LexGenerator.generate (LexGenerator.java:74)

 em jflex.Main.generate (Main.java:320)

 em jflex.Main.main(Main.java:336)

 sultoric

 50

 COCÔ

**Comment by lsf37** [comment]
Sorry, I don't speak Portugese (I assume this is Portugese) and this doesn't seem to be a version of JFlex I have written, so I can't help you with that.
