### ISSUE TITLE
[Bug] Lexers don't work anymore after migration from JFlex 1.4 to JFlex >= 1.5 (infinite loops) [sf#134]

### ISSUE THREAD

**Issue by lsf37** [jflex-de/jflex#135]
**Reported by thierryblind on 2015-01-13 23:42 UTC**
Hello,
I'm a committer for the eclipse PDT project (https://eclipse.org/pdt/) and I'm actually trying to migrate all the lexers (using JFlex 1.4) to use JFlex >= 1.5
Sadly I'm now facing infinite loops because some lexers don't seem to behave the same anymore.
I added as attachment a test project that contains some of the problematic lexers (in folder "parserTools"), the generated JFlex 14.3 and 1.5.1 classes, and a test case (src/launch/Tests.java).
Could you please have a look and tell me what's happening?
Thank you very much for your help,

Thierry.

**Comment by lsf37** [comment]
Attachment on SF tracker: http://sourceforge.net/p/jflex/bugs/134/attachment/JFlex_sample.zip

**Comment by lsf37** [comment]
This also looks related to #131, need to confirm.

**Comment by tbl0605** [comment]
Hi Gerwin,
thank you for looking into this bug. Actually I'm the reporter of this bug (Thierry Blind), but I'm using another account name on github :)
I don't know what you mean when you say it's related to #131, but for sure the fix for #131 (https://github.com/jflex-de/jflex/commit/9a226be2c4c62a6020dd9720b92c994ded221227) doesn't solve this bug! If I can help, tell me :)

Thierry.

**Comment by lsf37** [comment]
Thanks for checking. It seems that https://github.com/jflex-de/jflex/commit/9a226be2c4c62a6020dd9720b92c994ded221227 doesn't fix #131 either, so there is more to do in any case.

**Comment by tbl0605** [comment]
Only thing i can say is that bug was introduced after 1.4.3 release and is present since 1.5 release. Hope it can give you some clue! 

Thierry.

**Comment by lsf37** [comment]
Hi @tbl0605, it looks like the fix for issue #133 could apply to your problem, at least the warning I introduced for it in 6918cb3915b5d4e12e1efdb881ae6db8bc0d371e is triggered by your test case.

Could you check if the new version at f312d563777d907bbb12d1e2ac79835ba83ca53c still has your problem? (Should not need to fix the warning for that, although it may be a good idea in any case).

Background: after version 1.4.3 there was a feature request for the ability to match the empty string (JLex does so). Before that feature request I had excluded that, because it will usually lead to non-termination, but there are some legitimate uses for it. A side effect of the implementation was that empty matches take precedence over EOF actions, so they will always trigger at the end of input and if nothing else changes (e.g. lex state or similar), the scanner will loop.

f312d563777d907bbb12d1e2ac79835ba83ca53c makes EOF take precedence over empty matches.

**Comment by lsf37** [comment]
Forgot to say: be sure to use the new 'skeleton.nested' file if you have used the old one in your code. (Nothing special necessary if you haven't)

**Comment by tbl0605** [comment]
Hi Gerwini,
sorry, I don't get latest master version to compile :(

Buildfile: /root/git/jflex/jflex/build.xml
-generate-scanner:
    [jflex] Generated: LexScan.java
-generate-parser:
      [cup] This is CUP v0.11a beta 20060608
      [cup] Authors : Scott E. Hudson, Frank Flannery, Andrea Flexeder, Michael Petter and C. Scott Ananian
      [cup] Bugreports to petter@cs.tum.edu
      [cup] checking, whether this run is necessary
      [cup] Either Parserfile or Symbolfile didn't exist
      [cup] Parserfile build/generated-sources/jflex/LexParse.java isn't actual
      [cup] Symbolfile build/generated-sources/jflex/sym.java isn't actual
      [cup] Warning : Terminal "STRING_I" was declared but never used
      [cup] Warning : Terminal "CONCAT" was declared but never used
      [cup] Warning : Terminal "CCLASSNOT" was declared but never used
      [cup] Warning : Terminal "CHAR_I" was declared but never used
      [cup] Warning : Terminal "UNION" was declared but never used
      [cup] Warning : Terminal "CCLASS" was declared but never used
      [cup] ------- CUP v0.11a beta 20060608 Parser Generation Summary -------
      [cup]   0 errors and 6 warnings
      [cup]   60 terminals, 19 non-terminals, and 113 productions declared, 
      [cup]   producing 196 unique parse states.
      [cup]   6 terminals declared but not used.
      [cup]   0 non-terminals declared but not used.
      [cup]   0 productions never reduced.
      [cup]   0 conflicts detected (0 expected).
      [cup]   Code written to "LexParse.java", and "sym.java".
      [cup] ---------------------------------------------------- (v0.11a beta 20060608)
compile:
    [javac] Compiling 71 source files to /root/git/jflex/jflex/build/classes
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.5
    [javac] /root/git/jflex/jflex/build/generated-sources/jflex/LexScan.java:3391: error: 'else' without 'if'
    [javac]       else {
    [javac]       ^
    [javac] /root/git/jflex/jflex/build/generated-sources/jflex/LexScan.java:3457: error: orphaned default
    [javac]           default:
    [javac]           ^
    [javac] 2 errors
    [javac] 1 warning

BUILD FAILED
/root/git/jflex/jflex/build.xml:83: Compile failed; see the compiler error output for details.

**Comment by lsf37** [comment]
Ah, sorry, the new skeleton file creates a bootstrap problem in the `ant` build. Try renaming `skeleton.nested` to `skeleton.nested.new`, and for this build restore the old one with

    git checkout 3e8e0ed0e077ae9615808bee0df2a1ebdd0da6dc skeleton.new

(in sub directory `jflex/src/main/jflex`).

That should build jflex now and with that new jflex jar, you should be able to use `skeleton.nested.new`.

**Comment by tbl0605** [comment]
Hi Gerwin,
I managed to compile jflex with your help, thank you ;)
But I also had to modify the pom.xml file to rename the <plugins>...</plugins> section to <pluginManagement>...</plugins>
It seems that Eclipse Luna SR1 includes some version of maven m2e plugin that complains about the <plugins>...</plugins> section :

Plugin execution not covered by lifecycle configuration: de.jflex:jflex-maven-plugin:1.6.0:generate (execution: default, 
 phase: generate-sources)

My first tests are positive (no more infinite loops) and your new version nicely warns the user about expressions that could match empty strings, which is a very good point (even if we already test in our rules that yylength() > 0) :
     [java] Warning in file "highlighting_scanner-1.5.jflex" (line 993): 
     [java] Expression matches the empty string, which may lead to non-termination.
     [java] <ST_PHP_HEREDOC>{HEREDOC_CHARS}*({HEREDOC_NEWLINE}+({LABEL}";"?)?)? {

I will do some more tests and tell you if it's ok.
I saw that you're planning the 1.6.1 milestone for 27 februar, it will be a bit short for me to test your patch correctly, could you delay it a little bit, please ? :)

Thierry.

**Comment by lsf37** [comment]
Sure, no problem pushing it out a little. It looks like I won't be really ready in time either.

My maven foo is limited, I will have to read up on what the eclipse problem could be. @sarowe do you have experience with that?

**Comment by sarowe** [comment]
> But I also had to modify the pom.xml file to rename the ... section to ... It seems that Eclipse Luna SR1 includes some version of maven m2e plugin that complains about the ... section :

What are all the ...-s, Thierry?

I don't use Eclipse, so I'm not sure exactly what the problem is.  

Is this error occurring when you try to initialize your project from within Eclipse?

**Comment by tbl0605** [comment]
Hi Gerwin,
sorry my previous comment was wrongly formatted, I updated it.

And I'm also not a maven specialist ;) I found the solution by googling :
http://stackoverflow.com/a/13733232/2332350

And yes, problem occurs in eclipse when I convert the java project to maven project (because initially the jflex project imported from git is seen by eclipse as a "java project" and not as a "maven project"). After that, pom.xml is used to initialize the project and to compile the sources, but it fails because of the wrong < plugins >...< /plugins > section.

Thierry.

**Comment by tbl0605** [comment]
Hi Gerwin, Hi Steve,
I converted the different lexers of the PDT project to use latest master version of JFlex, and after few hours of test, I had no infinite loops.
For me this bug can be closed.

Thank you very much for your hard work on this nice software ! ;)

Thierry.

PS: should I open a bug report for the pom.xml < plugins >...< /plugins > problem ?

**Comment by lsf37** [comment]
Thanks for confirming! It would be nice to track the pom.xml separately. If you could open a new issue that would be great.

I'll close this one here.
