### ISSUE TITLE
Error in the pom.xml files when importing JFlex in eclipse Luna SR1

### ISSUE THREAD

**Issue by tbl0605** [jflex-de/jflex#170]
Hi,
when importing latest master version of JFlex in eclipse Luna SR1 and converting the jflex and jflex-maven-plugin subprojects as maven projects, I get following error in the pom.xml files :

Plugin execution not covered by lifecycle configuration: de.jflex:jflex-maven-plugin:1.6.0:generate (execution: default, phase: 
 generate-sources)

Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-antrun-plugin:1.7:run (execution: cup-
 generate-parser, phase: generate-sources)

Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-plugin-plugin:3.2:descriptor (execution: 
 default-descriptor, phase: generate-resources)

Eclipse doesn't seem to like the < plugins >...< /plugins > section in both pom.xml files.
Replacing this section by < pluginManagement >...< /pluginManagement > seems to do the trick for the jflex subproject, but sadly not for the jflex-maven-plugin subproject.

Thierry.

**Comment by lsf37** [comment]
Thanks. Looks like I should download eclipse again once more and have a closer look at what is going on.

**Comment by regisd** [comment]
This seems to be a recurring problem with m2eclipse and Maven https://www.eclipse.org/m2e/documentation/m2e-execution-not-covered.html http://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

**Comment by lsf37** [comment]
Thanks for fixing this! Would have cost me a lot more time to dig into.
