### ISSUE TITLE
LexScan.java:[3356,7] 'else' without 'if'

### ISSUE THREAD

**Issue by regisd** [jflex-de/jflex#171]
Just checkout out master at commit c507d2ec46a35f3da1d22f3288658c251d0c13f2

`mvn compile` fails on project *jflex* with:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project jflex: Compilation failure: Compilation failure:
[ERROR] /Users/regisd/workspace_jflex/jflex-parent/jflex/target/generated-sources/jflex/jflex/LexScan.java:[3356,7] 'else' without 'if'
[ERROR] /Users/regisd/workspace_jflex/jflex-parent/jflex/target/generated-sources/jflex/jflex/LexScan.java:[3427,11] orphaned default

**Comment by regisd** [comment]
I think this is related to issue #133

**Comment by lsf37** [comment]
It's a bootstrap problem: I changed the skeleton file, and it is now incompatible with jflex 1.6. I just need to push out the current snapshot jar, and update the dependencies, then things should work again. 

Am not at a computer right now, but should be in a few hours.

**Comment by lsf37** [comment]
Opted to keep the old `skeleton.nested` around to not get into cyclic dependency issues. Build should now work again.

**Comment by MartinWalch** [comment]
Are you aware that this bug is present in 1.6.1?
It is not possible to bootstrap 1.6.1 using 1.6.1 itself.

**Comment by lsf37** [comment]
Yes, that's what my comment from March 1 meant to say.

In general, JFlex version x does not usually bootstrap with version x, but the version before. The plan is that `1.7.0` will bootstrap with `1.6.1`.

**Comment by MartinWalch** [comment]
Alright. Wouldn't it be then appropriate to ship the version needed for building with the source tarball?
