### ISSUE TITLE
Generated scanner does include an InputStream constructor

### ISSUE THREAD

**Issue by fror** [jflex-de/jflex#173]
The [changelog](http://jflex.de/history.html) says that `By default no InputStream constructor is included in the generated scanner. The capability to include one is deprecated and will be removed in JFlex 1.7.`

When I build my project using Maven (including the jflex plugin 1.6.0), I keep getting a warning saying `Warning: Emitting deprecated InputStream constructor. The inputstreamctor option will cause this constructor to be emitted in JFlex 1.6; the version after 1.6 will never emit this constructor.` As a "side"-effect, an InputStream contstructor is indeed created.

I could isolate the issue to the following small code. As you can see, there is no indication that I specifically want an `InputStream` constructor. But I still receive the warning.

    package tmp;

    %%
    %class Lexer
    %function nextToken
    %type Token
    %yylexthrow ParseException
    %{
    %}
    %%
    &lt;YYINITIAL> {
      "a"  { return new Token(); }
    }

My pom.xml:

    <project>
        <build>
            <plugins>
                <plugin>
                    <groupId>de.jflex</groupId>
                    <artifactId>jflex-maven-plugin</artifactId>
                    <version>1.6.0</version>
                    <executions>
                        <execution>
                            <goals>
                                <goal>generate</goal>
                            </goals>
                        </execution>
                    </executions>
                </plugin>
            </plugins>
        </build>
    </project>

**Comment by lsf37** [comment]
Yes, there seems to be an inconsistency between the warning text and the changelog text. 

If I remember correctly (have to look into it), you should not get an input stream constructor by default, but you should get a warning that you're not getting one (because that was new in 1.6). The warning text doesn't quite match that.

**Comment by lsf37** [comment]
I could not reproduce the problem with 1.6.0 and 1.6.1-SNAPSHOT and the code doesn't look like the warning should happen. By default I get no InputStream constructor and no warning. The warning does appear when I set the option (as it should).

Are you sure that there is no parent pom in the project that sets `inputStreamCtor` globally?

**Comment by fror** [comment]
Here's the shortest project I could make with this issue: https://github.com/fror/jflex-issue-173.

**Comment by sarowe** [comment]
Thanks, fror, for the example project.  I was able to reproduce as-written (i.e. using jflex-maven-plugin 1.6.0) on Windows 7 with Maven 2.2.1, 3.1.0 and 3.2.5, and also on OS X 10.10.2 with Maven 3.2.5.

I'll try to repro with 1.6.1-SNAPSHOT later this weekend.

**Comment by fror** [comment]
The commit ba09da5e37c9f3589254a497862c219bc24f7dba fixes the issue. It was performed on the same day of the release, but *after* the release, according to this diff: https://github.com/jflex-de/jflex/compare/release_1_6_0...master so the current version 1.6.1-SNAPSHOT actually fixes this issue.

I've tested using the version 1.6.1-SNAPSHOT from master HEAD with my project above mentioned and the warning has disappeared so did the "InputStream" constructor.

This actually closes this issue.

**Comment by lsf37** [comment]
Awesome, thanks for figuring this one out.
