### ISSUE TITLE
Make generated code pass doclint

### ISSUE THREAD

**Issue by bobbylight** [jflex-de/jflex#182]
While I have yet to find anyone who actually likes it, doclint is enabled by default when compiling with JDK 8.  It would be nice if generated lexers passed doclint inspection without errors or warnings.

**Comment by lsf37** [comment]
Yes, I agree, we should aim for that.

**Comment by regisd** [comment]
The no-@param waring is particularly annoying. If the param is obvious and I don't want to document it, adding `* @param paramName` is really useless.

**Comment by regisd** [comment]
@lsf37 I propose to move this to the 1.8.0 release, and consider 1.8.0 targets Java 8.

It's a long time we haven't released anything, and I think this one might take time.

**Comment by regisd** [comment]
I've started to fix our own code in https://github.com/jflex-de/jflex/tree/doclint (with many dumb auto-generated javadoc) and I don't see errors in generated code.

**Comment by lsf37** [comment]
I'm happy to postpone it to 1.8.0, it shouldn't hold up the release.

**Comment by lsf37** [comment]
Um, sorry, just saw that it's already mostly fixed. I'm Ok with using the generated comments and then keep working on improving them over time.
