### ISSUE TITLE
jflex --{version,info,help} should exit with code 0 (success)

### ISSUE THREAD

**Issue by asmod3us** [jflex-de/jflex#194]
Title really says it all. In a bash shell, 
```
jflex --version
echo $?
```

will display the version and 1, i.e. a non-zero exit code. Non-zero exit codes usually indicate an error (see e.g. `grep --version; echo $?`), so it would be more idiomatic to exit with code 0.

**Comment by lsf37** [comment]
Yes, it would make a lot of sense to do that. Have put it on the list of things to do for the next release.
