### ISSUE TITLE
How to create regex to match content start with <

### ISSUE THREAD

**Issue by LichFaker** [jflex-de/jflex#198]
I am using JFlex 1.4.3, when I write regex with '<' in flex file, the scanner seem does not work

**Comment by schedulix** [comment]
In my scanner I use a symbol

cmpop   =       ">"|"<"|">="|"<="|"=="|"<>"|"!="|"=~"|"!~"
...
<YYINITIAL>{cmpop}                      { /* do something */ }

which works perfectly with all jflex versions so far. (I think I started with 1.4.0; not sure though)

HTH

Ronald

**Comment by LichFaker** [comment]
However, I use `Comment= <!--[\w\W\r\n]*?-->` can't match html comment

**Comment by schedulix** [comment]
Just for the sake of the experiment, you could write something like

`Comment = [<]!--[\w\W\r\n]*?--[>]`

Apart from that, I wouldn't try to match an entire HTML comment with a single RE. In general HTML comments can be very complex and contain all kinds of characters. Even if you know what to expect now, this could change in the future. And never ever trust your users. They'll figure out something you didn't think of. ;-)
And I also don't understand why you write `[\w\W\r\n]*?`. The asterisk already means "zero to n". So get rid of the question mark.

**Comment by LichFaker** [comment]
Thank you very much, it works! 
Well, I am going to develop an highlighter intellij plugin for a custom language which is similar to xml.
And lots of plugins use JFlex to do lexical analysis. It was a bit difficult for me, because I just started recently.
