### ISSUE TITLE
Fixes code point counting in supplementary unicode characters

### ISSUE THREAD

**Issue by ikarienator** [jflex-de/jflex#200]
For example, a unicode C-style character should look like this:

```
"\'" ([^\'\\\n\r] | \\ [tvrnfb\\'\"]) "\'"
```

But this would not work for `'😆'`.

**Comment by lsf37** [comment]
Hi @ikarienator, I'm not sure what you're asking. Are you saying that `%column` and/or `%line` counts are wrong when these characters are present or that your expression doesn't match what it should match?

**Comment by regisd** [comment]
Close due to lack of activity.
