### ISSUE TITLE
question on ignoring \v (^K)

### ISSUE THREAD

**Issue by tarzanek** [jflex-de/jflex#202]
Hi
I have a text file containing ^K  (char 11 , vertical tab)
and I'd like to capture this character
I tried defining
\v
[\v]
but nothing helps, parser always dies on this character no matter how I try to define it

any guidance?
Fwiw - source:
https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/analysis/erlang/ErlangXref.lex

I tried adding \v to whitespace definition and even just as alone char , but no luck :(

the text causing above to fail:
'''
r() ->
<<"ab">> = iolist_to_binary()
'''
- the char between a and b is ^K

**Comment by tarzanek** [comment]
any guidance will help, it seems I don't understand something obvious :(

**Comment by sarowe** [comment]
`\v` is not a supported escape sequence - see http://jflex.de/manual.html#LexRules

You have a few alternatives:
`\u000B`
`\x0B` 
`\u{B}` <- this will work in JFlex 1.6.0+

**Comment by tarzanek** [comment]
thanks Steve, I'll give it a try

**Comment by tarzanek** [comment]
lovely , works, thanks for the pointer I am completely blind, didn't see that the list of escape sequences doesn't contain \v
