### ISSUE TITLE
on limits of current input

### ISSUE THREAD

**Issue by tarzanek** [jflex-de/jflex#203]
Hi Steve
quick Q
I would like to comply my lexical parsers with lucenes limit of 32766 bytes per token
is there a way how I can tell jflex to drop the token(ideally stop parsing and find it's "end") if it becomes > 32766 bytes somehow ?
(jflex saves the position, so a position check within one line would be ideal)

thank you
L

**Comment by tarzanek** [comment]
regarding dropping the token and finding the end of it - it would be completely fine if jflex would drop whole line if it finds it has a token > 32766 bytes ... (or the line itself is > 32766 bytes)
and just jump to next line

**Comment by sarowe** [comment]
Hi Lubos, 

Lucene's StandardTokenizer uses a hacked version of JFlex's generated scanner to limit token length to the buffer size, which is not allowed to grow.  This would not meet your needs though, since it *splits* long tokens at an arbitrary max length, rather than ignoring them.  See the Lucene issue that precipitated this change: https://issues.apache.org/jira/browse/LUCENE-5897 and also JFlex issue #197 to incorporate this capability into JFlex itself (not yet implemented).

Prior to LUCENE-5897, the Lucene StandardTokenizer, which wraps the generated JFlex scanner, simply threw away tokens above the (configurable) maxTokenLength limit - would that be feasible?  If you did this, then you wouldn't have to address the problem in every JFlex grammar.

Steve

**Comment by tarzanek** [comment]
yes, second solution would probably work, I just need to figure out how to incorporate it into how we use jflex in {OpenGrok
thank you, will have a look and ask if I will miss something :)

cheers
L

**Comment by tarzanek** [comment]
fwiw - splitting might work too, but then I'd still have the performance hit of parsing file with veeeery long lines + who is interested in such huge lines anyway (in scope of source code)?
hence second option seems more like a win solution

**Comment by tarzanek** [comment]
@sarowe will you eventually get what macro <macrodef name="run-jflex-and-disable-buffer-expansion">
in https://issues.apache.org/jira/secure/attachment/12663628/LUCENE-5897.patch does to jflex ?
I think it would be a fix for this and would cleanup the build files for lucene ... (it's kinda tricky to patch generated files from build files)

**Comment by sarowe** [comment]
@tarzanek yes, I do still plan on bringing this capability to JFlex.

**Comment by tarzanek** [comment]
great :)
looking forward, I had finally a look and it seems the limit on zzbuffer size + patch from that macro will get a fix for us too,
The only concern is sustainability of such "patch", which definitely is not obvious and any new jflex version will break it ... (so if you get it to jflex all this build.xml hacks will be gone and all will live happily ever after :-D )

**Comment by tarzanek** [comment]
btw. it's interesting that most lucene analyzers set the max token to 1MB, and the code that adds docs only allows 65536 chars in token, so this makes 65536 UTF16 chars as max ... OK :)

**Comment by tarzanek** [comment]
just a note that patch https://issues.apache.org/jira/secure/attachment/12663628/LUCENE-5897.patch applies only to jflex 1.6.0 
it seems jflex 1.6.1 needs new patch

**Comment by tarzanek** [comment]
@sarowe I modified the patch to fit 1.6.1 just by changing 
totalRead to numRead :


                <replaceregexp file="${src.generatedsrc.dir}/@{dir}/@{name}.java"
                               match="(zzFinalHighSurrogate = 1;)(\r?\n)"
                               replace="\1\2          if (numRead == 1) { return true; }\2"/>         

is that OK ? it seems it works, so I hope I didn't set up any landmines

Another silly lucene Q is that I didn't use position incrementing from above patch, but we use 
    @Override
    public final boolean incrementToken() throws IOException {
        return this.yylex();
    }
so I expect this would still work (though I expect higlighting modules might be confused by such analyser)
is it safe to use yylex() as a way to increment token even with above buffer/token "skipping" in place?

**Comment by tarzanek** [comment]
(fwiw I took the totalRead to numRead from : 
https://github.com/jflex-de/jflex/commit/9a226be2c4c62a6020dd9720b92c994ded221227 )

**Comment by lsf37** [comment]
#1045 now implements the token size limit directly in JFlex using the `%token_size_limit` directive. That means, after the 1.9.0 release the manual should no longer be necessary.
