### ISSUE TITLE
Is ['] a valid character class? 

### ISSUE THREAD

**Issue by billfen** [jflex-de/jflex#210]
If so, it apparently does not work.  
Nor does [^']
I also tried [\'] and [^\'] without success.
It gets worse -  [\"] doesn't work either.   Or [^\"]

Based on a careful reading of the Manual, it looks to me as if [\"] and ['] and [^'] and [^"'] should all be legal.  Currently they fail with "unexpected character."

I looked thru LexScan.flex without seeing anything easily fixable.

Let me know if you want a test case.

**Comment by billfen** [comment]
Please close this - User error, due to an unbalanced brace some lines above.
Sorry for the noise.

**Comment by sarowe** [comment]
Thanks for letting us know the resolution, @billfen .
