### ISSUE TITLE
Maven warns that plugin not thread safe

### ISSUE THREAD

**Issue by dheid** [jflex-de/jflex#211]
When I execute mvn package -T8, the following warning will be displayed:

[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that are not marked as       *
[WARNING] * @threadSafe to support parallel building.                     *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in XXX:
[WARNING] de.jflex:jflex-maven-plugin:1.6.1
[WARNING] *****************************************************************

**Comment by lsf37** [comment]
@sarowe, do you know what is involved in maven's model for thread safety?

All the static settings in the Option class will probably interfere, so this does look like a bit of work to implement.

**Comment by sarowe** [comment]
I looked into it a little bit - essentially it must be possible to run more than one instance of the plugin simultaneously.  I think this is always/only in the context of multi-module builds, where more than one module is concurrently invoking the same plugin.
