### ISSUE TITLE
Macros in character classes are not supported

### ISSUE THREAD

**Issue by dscorbett** [jflex-de/jflex#216]
Using a macro in a character class produces the error message “Macros in character classes are not supported.” This contradicts [the documentation](http://jflex.de/manual.html#Grammar):

> ```
> CharClassContent    ::= CharClass | Character |
>                         Character'-'Character | 
>                         MacroUsage | PredefinedClass
> ```
> a character class [...] matches any character in that class. A Character is considered an element of a class if it is listed in the class or if its code lies within a listed character range Character’-’Character or Macro or predefined character class.

**Comment by lsf37** [comment]
I've been looking at it and it will need a refactor of a whole bunch of code. Nothing too hard, just a lot of work. Still planning to do that, but it's definitely going to be more than 1-2 months, given that I won't have much time to actually work on it.

**Comment by Jezza** [comment]
Ah, that's good to hear.

I thought it was just dead.  
There's no rush, I've actually just spent the last hour or two restructuring the lexer so I don't have to manually expand them.  
It makes it nicer in the end, so I guess it worked out in the end.

**Comment by lsf37** [comment]
Excellent, good to hear that you're not blocked on it any more. Still planning to work on it anyway, of course.

**Comment by wdanilo** [comment]
Is there any progress with this issue? It's really bad thing right now. Even allowing macros which point to simple character classes would help design the lex input much much nicer.

**Comment by lsf37** [comment]
Main refactor is done and first rough implementation of the feature is there. Currently in debugging.

**Comment by regisd** [comment]
Let me know when you need a code review.
