### ISSUE TITLE
%include files mtimes are not checked by JFlexTask

### ISSUE THREAD

**Issue by idodeclare** [jflex-de/jflex#217]
Hello,

A useful enhancement will be to compare also any %include files' lastModified() w.r.t. destFile in the anttask.

Regards.

**Comment by regisd** [comment]
Hello, I see you are using POM. Can you consider using the jflex-maven-plugin? I believe it shouldn't have this issue.

**Comment by idodeclare** [comment]
Thank you — I already have an ant workaround.

This issue is strictly regarding an issue with JFlexTask.
