### ISSUE TITLE
Update jdk to openjdk8

### ISSUE THREAD

**Issue by regisd** [jflex-de/jflex#225]
JFlex is currently compiled with openjdk7.

More and more Maven plugins are compiled with Java 8, and we cannot use them as a result.

Consider moving to openjdk8

**Comment by regisd** [comment]
This doesn't imply upgrading `${jflex.jdk.version}` AFAIK

**Comment by regisd** [comment]
Note this would make #186 infeasible.

**Comment by regisd** [comment]
And there was a problem with java 8 and unicode. See #209

**Comment by lsf37** [comment]
It'd be nice if we could provide support for older jdks as long as that is feasible. If our dependencies force us to move up the minimum requirements, then there is not much we can do, of course.

I just checked in #186 which versions are currently around in Travis, and it's basically only openjdk7 and openjdk8. We should make sure things work on openjdk8 for the next release. It sounds like #209 is solved now, so there if I'm interpreting things correctly, there is only the change in `isJavaIdentifier` in Java 8 that messes things up, and I'd argue that the new test output is correct, i.e. it should change together with the jdk version.

This means we should make the test suite aware of the jdk version and allow different outputs depending on jdk, or run it conditionally based on jdk, or something in that vein.

**Comment by lsf37** [comment]
We now have a working test for both (jdk7 and jdk8).

I think this satisfies this issue as well: we can drop jdk7 when our dependencies stop working, and we should make sure jdk8 remains functional.

**Comment by lsf37** [comment]
( @regisd  feel free to re-open if you disagree, of course )
