### ISSUE TITLE
sonatype deployment broken

### ISSUE THREAD

**Issue by lsf37** [jflex-de/jflex#315]
It looks like a few things changed slightly since the last time we deployed a release on sonatype.

After a few smaller updates (setting repo URL), and after a successful `./mvn-deploy` run, the sonatype website complains about the following when I stage the release:
  - missing javadoc
  - missing sources
  - missing gpg signature

I think I can address the gpg myself, but I'm a bit lost at the other two artefacts, because I thought we do produce them already. The might just be tweak needed in one of the `pom.xml` files, but without digging into them much more deeply, I couldn't see what exactly.

**Comment by lsf37** [comment]
@regisd -- do you know enough about maven to see what is missing there without digging too deep?

Unfortunately this means I won't be able to finish the release today, but I should be able to have another look next week, potentially tomorrow already.

**Comment by regisd** [comment]
Those artifacts are not built automatically, I've updated the release doc in PR #321

**Comment by lsf37** [comment]
No worries, if there is one thing I've learned about build systems, then it is that all of them suck in some way :-)

I was almost at the end of the release process, but abandoned the branch and deleted the tag after I ran into the deployment problems. I might take the time to update the instructions a bit more and maybe add a script for packing up the zip+tar files (the one I had locally is not going to work any more, and it's better to put it in the repo anyway).

**Comment by regisd** [comment]
OK, so the release branch is https://github.com/jflex-de/jflex/tree/branch-1.7.0 but I haven't done anything special on it.
Don't forget to merge #320 in master before running the `post-release.pl`, so that the `aggregated-java-sources` is updated automatically (hopefully)

**Comment by lsf37** [comment]
I've started another test deployment. It did generate javadoc and and source jars, but didn't pick them up for upload.

Ran out of time for today, will look at it again tomorrow.

**Comment by regisd** [comment]
Hmmm. According to http://maven.apache.org/plugins/maven-deploy-plugin/examples/deploying-sources-javadoc.html
```sh
mvn org.apache.maven.plugins:maven-deploy-plugin:2.8.2:deploy-file -Durl=file:///home/me/m2-repo \
                                                                            -DrepositoryId=some.repo.id \
                                                                            -Dfile=./path/to/artifact-name-1.0.jar \
                                                                            -DpomFile=./path/to/pom.xml \
                                                                            -Dsources=./path/to/artifact-name-1.0-sources.jar \
                                                                            -Djavadoc=./path/to/artifact-name-1.0-javadoc.jar
```

This looks ugly.

**Comment by lsf37** [comment]
So I'm making some (slow) progress on this. Turns out I (almost) lost my private key for the release signature, which explains the trouble I had with the gpg plugin. Now managed to restore it from backup and that part is fine. Now back to automating the source and javadoc deploy.

I still need to address a few small code cleanup things for the two features that still went into 1.7.0.

**Comment by regisd** [comment]
Sorry I can't help more here.
I guess we should automate the release of the SNAPSHOTs in the future, so that you don't suffer every 2 years when there is an actual release.

**Comment by lsf37** [comment]
That might help, although javadoc, sources, and signing are exactly the things we'd leave out for SNAPSHOTs :-)

**Comment by regisd** [comment]
True, Only releases can be uploaded to the central repository.

**Comment by lsf37** [comment]
They do, it’s just that the docs that I found for deployment specifically recommended leaving out java doc and sources to speed things up. Doesn’t mean we’d have to do that, of course. Signing is different, because it does need the private key and passphrase.

**Comment by regisd** [comment]
- I don't think we are killing Travis with a few builds per year. I'd like to have a more comprehensive regular build, and avoid last minute surprises when we deploy
- I'd rather reduce the build matrix (it also makes the CI deploy phase more complex, because we don't want to run it on every cell of the build matrix. I'm trying to simplify that in #332 btw)
- The private key can probably be saved in Travis, like we do with the GITHUB_TOKEN
