### ISSUE TITLE
Copy over cup license in release

### ISSUE THREAD

**Issue by lsf37** [jflex-de/jflex#357]
java_cup is redistributed
- in aggregated-java-sources
- in shaded jar
- in global .tar.gz distribution

In this case, the CUP license should be shipped too.

**Comment by regisd** [comment]
Done for aggregate-java-sources with #353 (commit 0e44dda12af93bd53ddd278516eca7fee4025e4d)

**Comment by regisd** [comment]
I think #393 indirectly fixes this issue (but I didn't verify).
