### ISSUE TITLE
[1.7.0] download links not working on jflex.de

### ISSUE THREAD

**Issue by jannick0** [jflex-de/jflex#367]
On http://jflex.de/download.html the download links for the 1.7.0 package  are not working (ERROR 403).

**Comment by lsf37** [comment]
Well, that is embarrassing.. Should be fixed now!

**Comment by regisd** [comment]
Thanks jannick0.
I'll mark this bug invalid because it is in project jflex-de/jflex-web (in this case, I suppose the .tar.gz was simply missing ; but I confirm @lsf37 fixed the download link)

**Comment by lsf37** [comment]
Just to confirm for posteriority: the file wasn't missing, just had insufficient permissions (600 instead of 644).
