### ISSUE TITLE
ant build doesn't support jUnit @Test annotation

### ISSUE THREAD

**Issue by regisd** [jflex-de/jflex#376]
A simple test class using junit 4 `@Test` annotations passes in the Maven build, but fails with ant build

>     [junit] 	Caused an ERROR
>     [junit] org/hamcrest/SelfDescribing
>     [junit] java.lang.NoClassDefFoundError: org/hamcrest/SelfDescribing
>     [junit] 	at java.lang.ClassLoader.defineClass1(Native Method)
>     [junit] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
>     [junit] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
>     [junit] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
>     [junit] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
>     [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
>     [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
>     [junit] 	at java.security.AccessController.doPrivileged(Native Method)
>     [junit] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
>     [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>     [junit] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
>     [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
>     [junit] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
>     [junit] Caused by: java.lang.ClassNotFoundException: org.hamcrest.SelfDescribing
>     [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:359)
>     [junit] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
>     [junit] 	at java.security.AccessController.doPrivileged(Native Method)
>     [junit] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
>     [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
>     [junit] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
>     [junit] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)

https://travis-ci.org/jflex-de/jflex/jobs/432894291

**Comment by regisd** [comment]
I see one alternative

- either get rid of ant – having multiple build systems increases the maintenance cost for not huge benefit
- or use ivy for dep management in the ant build

**Comment by lsf37** [comment]
I'll have a look at this, but am away for a few days (back end of next week), so will be slow.

**Comment by regisd** [comment]
I have a solution with ivy.

**Comment by lsf37** [comment]
The solution with ivy works fine in the `simple` example, so I think we can close this issue and use that for the other examples as well where necessary.
