### ISSUE TITLE
Travis doesn't test all examples

### ISSUE THREAD

**Issue by regisd** [jflex-de/jflex#383]
Change #373  reformatted the source code of the examples.

However, the `examples/java` uses its own source code as an example of a java parser.

By changing the lines, the golden file is now wrong.
Travis didn't detect that `make test` now returns "Test failed"

**Comment by regisd** [comment]
I suspect that `@(diff expected.txt actual.txt && echo "Test OK!") || echo "Test failed!"` always returns true because `echo` is always successful.

**Comment by regisd** [comment]
Also, I'm not sure whether travis actually runs the `make` examples.

**Comment by lsf37** [comment]
Yes, the line will always return true. Something like

```sh
@(diff expected.txt actual.txt && echo "Test OK!") || (echo "Test failed!"; exit 1)
```

should work. I'm not sure either about travis, I thought it did run them, but I could be wrong.

**Comment by lsf37** [comment]
I can have a look at these when I'm back if you want.

**Comment by regisd** [comment]
I'll send a PR to better cover the tests.

But please have a look on #384. I don't understand why the CupAntTask doesn't generate the same code as the cup-maven-plugin
