### ISSUE TITLE
CupAntTask generates incorrect code: java_cup.runtime.Symbol cannot be cast to ComplexSymbolFactory$ComplexSymbol

### ISSUE THREAD

**Issue by regisd** [jflex-de/jflex#384]
The code generated by the CupAntTask has the advanced symbol management (http://www2.cs.tum.edu/projekte/cup/manual.html#advanced-symbols)

This causes all the examples to fail with

>      [java] Parsing [src/main/java/TestLexer.java]
>      [java] java.lang.ClassCastException: java_cup.runtime.Symbol cannot be cast to java_cup.runtime.ComplexSymbolFactory$ComplexSymbol
>      [java] 	at parser$CUP$parser$actions.CUP$parser$do_action_part00000000(Unknown Source)
>      [java] 	at parser$CUP$parser$actions.CUP$parser$do_action(Unknown Source)
>      [java] 	at parser.do_action(Unknown Source)
>      [java] 	at java_cup.runtime.lr_parser.parse(lr_parser.java:699)
>      [java] 	at JavaParser.main(Unknown Source)

**Comment by regisd** [comment]
PR #430 encounters this problem.
https://travis-ci.org/jflex-de/jflex/jobs/439849615

**Comment by regisd** [comment]
The problem is that `cup-interpreter` loads cup twice:
```
  <property name="java_cup" value="../../../cup/cup/java-cup-11b.jar"/>
  <property name="jflex" value="../../target/jflex-full-1.7.1-SNAPSHOT.jar"/>
```

**Comment by regisd** [comment]
This is also suspicious
> warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds

**Comment by jandrovins** [comment]
Any news about this?

**Comment by regisd** [comment]
I'm still puzzled by the change. I'm not going to investigate this issue, if you can help, that would be great.
And maybe @sarowe knows how to change the behavior of the CupAntTask.

**Comment by lsf37** [comment]
Still investigating, but it looks like Stefan really wants people to use the new SymbolFactory interface, the old constructor without factory is deprecated.

**Comment by lsf37** [comment]
Alright, the culprit is the new `Location` class that you can choose to use instead of the older `symleft`/`symright` interface. The `Location` way expects you to use `ComplexSymbolFactory`, and the ant build defaults to `-locations` whereas command line and maven default to `locations` being off.

**Comment by lsf37** [comment]
So, the simple fix is to turn 

```
  <target name="cup">
    <cup srcfile="src/main/cup/parser.cup" interface="yes" destdir="antbuild"/>
  </target>
```

into

```
  <target name="cup">
    <cup srcfile="src/main/cup/parser.cup" interface="yes" locations="false" destdir="antbuild"/>
  </target>
```

which I will do for now.

The longer-term fix is to use the new symbol factory interface. It's being used and generated by Cup either way already, but only the `-locations` option requires the symbol class to be an instance of `ComplexSymbolFactory$ComplexSymbol`.
