### ISSUE TITLE
 Failure to find de.jflex:cup_runtime:jar:11b

### ISSUE THREAD

**Issue by ambs** [jflex-de/jflex#390]
Hi. I'm new to Java and all these new ways to automate builds. I am trying to build a simple project in IntelliJ IDEA. I configured Maven as described in the documentation. Nevertheless, when running the compile step, I get 

org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal de.jflex:jflex-maven-plugin:1.7.0:generate (default) on project pt-flex: Execution default of goal de.jflex:jflex-maven-plugin:1.7.0:generate failed: Plugin de.jflex:jflex-maven-plugin:1.7.0 or one of its dependencies could not be resolved: Failure to find de.jflex:cup_runtime:jar:11b in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

Any help is welcome.

**Comment by regisd** [comment]
Our mistake, we didn't publish **de.jflex:cup_runtime**.
@lsf37 I don't have permissions to do this, so I'm afraid this problem falls on you.

**Comment by regisd** [comment]
@ambs Thanks a lot for reporting the problem! We didn't deploy one of our internal dependency.

I see two options to use JFlex on your project
- use jflex version 1.6.1 (instead 1.7.0) until this bug is fixed.
- install jflex from sources:
  ```
    git clone --branch v1.7.0 --depth 1 https://github.com/jflex-de/jflex.git 
    cd jflex
    ./mvnw install
  ```

**Comment by ambs** [comment]
Thanks. Will try 1.6.1 for now, as it is easier to explain to students.

**Comment by regisd** [comment]
Let's follow-up in #400

**Comment by lsf37** [comment]
Sorry about all this, I'm looking into it now. It seems the pom file for cup explicitly tells it to skip deployment, but I guess that should only apply to cup itself and not the runtime.

**Comment by lsf37** [comment]
So, I've manually deployed cup_runtime and cup-parent 11b. For some reason maven still does not find cup-parent even though it does find and download the pom and the jar for cup_runtime.

Maybe it just needs some more time to sync, but why it would sync only one and not the other mystifies me. Will give it a bit more time.

**Comment by lsf37** [comment]
And now it's there and seems to work.

The reason I didn't catch this in my release testing is that maven caches things locally, which means all dependencies were present on my machine and it didn't try to download them.

**Comment by regisd** [comment]
https://repo.maven.apache.org/maven2/de/jflex/cup_runtime/

**Comment by ulenkar** [comment]
Just to let you know - I've just had the same problem and solved it by installing jflex from sources.
