### ISSUE TITLE
Suspicious change in the lexer with JDK 9

### ISSUE THREAD

**Issue by regisd** [jflex-de/jflex#398]
@lsf37  Gerwin, changing the JDK changed the generated `ZZ_CMAP_PACKED`.
See `jflex/LexScan.java` in commit db55da61d3570d0027a3518b6e745ed6cb7f53df

Is this expected?

**Comment by lsf37** [comment]
I can confirm that the definition of Java identifier has changed [https://blogs.oracle.com/sundararajan/underscore-is-a-keyword-in-java-9,-use-this-script-to-check-your-code], so this change in the character class is expected.
