### ISSUE TITLE
Source option 5 is no longer supported. Use 6 or later.

### ISSUE THREAD

**Issue by regisd** [jflex-de/jflex#400]
Reported by @ambs

> ```
> [ERROR] Source option 5 is no longer supported. Use 6 or later.
> [ERROR] Target option 1.5 is no longer supported. Use 1.6 or later.
> ```

**Comment by regisd** [comment]
I think this means that
- You are using JDK9 or later
- Your project uses **maven-compiler-plugin** with an old version which defaults to Java 5.

You have three options to solve this
1.  Downgrade to **JDK7** or **JDK8** (meh)
2.  Use **maven-compiler-plugin** version or later, because
   > **NOTE:** Since 3.8.0 the default value has changed from 1.5 to 1.6
    See https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#target
    ```
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <version>3.8.0</version>
        </plugin>
    ```
3.  Indicate to the **maven-compiler-plugin** to use source level 6 and target 6 (or later).
    **Best practice** recommended by https://maven.apache.org/plugins/maven-compiler-plugin/index.html
    > Also note that at present the default source setting is 1.6 and the default target setting is 1.6, independently of the JDK you run Maven with.
    > You are highly encouraged to change these defaults by setting source and target as described in [Setting the -source and -target of the Java Compiler.](https://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html)
    ```
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-compiler-plugin</artifactId>
            <configuration>
                <source>1.5</source>
                <target>1.5</target>
            </configuration>
        </plugin>
    ```
    or use
    ```
      <properties>
        <maven.compiler.source>1.6</maven.compiler.source>
        <maven.compiler.target>1.6</maven.compiler.target>
      </properties>
    ```

**Comment by ambs** [comment]
Hi. Thanks, will try. I am using IntelliJ IDEA 2018.2 with JDK 11. No idea what version maven-compiler-plugin it uses.
I will try option 3 and give details soon. THanks

**Comment by regisd** [comment]
IntelliJ will use whatever the pom says. What are you trying to compile?
If you try to build the examples, then yes, they didn't support JDK9+
I also use option 3 when I added support for JDK 9 in #363

**Comment by ambs** [comment]
I am trying a simple jflex file. The pom just refers the jflex 1.6.1, nothing more. As soon as I reboot to windows I'll give it a new try.

**Comment by kareemjeiroudi** [comment]
The second option in [@regisd 's answer](https://github.com/jflex-de/jflex/issues/400#issuecomment-425849840) worked for me. The first option where you specify the configuration of a plugin didn't when using the JavaFX `openjfx` plugin :(.

**Comment by MerveRida** [comment]
The second option in [@regisd](https://github.com/jflex-de/jflex/issues/400#issuecomment-425849840) 's answer also worked for me. I tried the third option as well but somehow that one didn't work, fyi.
