### ISSUE TITLE
examples/simple ant run fails with ExecuteJava can not access a member of class Yylex with modifiers "public static"

### ISSUE THREAD

**Issue by regisd** [jflex-de/jflex#429]
Steps:
```
cd jflex/examples/simple
ant run
```

Expected:
Execute Yylex

Actual:
> build:
>     [javac] /Users/regis/Projects/jflex/jflex/examples/simple/build.xml:25: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
> 
> run:
>      [java] java.lang.IllegalAccessException: Class org.apache.tools.ant.taskdefs.ExecuteJava can not access a member of class Yylex with modifiers "public static"
>      [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:194)
>      [java] 	at org.apache.tools.ant.taskdefs.Java.run(Java.java:861)
>      [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:231)
>      [java] 	at org.apache.tools.ant.taskdefs.Java.executeJava(Java.java:135)
>      [java] 	at org.apache.tools.ant.taskdefs.Java.execute(Java.java:108)
>      [java] 	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
>      [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>      [java] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>      [java] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>      [java] 	at java.lang.reflect.Method.invoke(Method.java:498)
>      [java] 	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
>      [java] 	at org.apache.tools.ant.Task.perform(Task.java:350)
>      [java] 	at org.apache.tools.ant.Target.execute(Target.java:449)
>      [java] 	at org.apache.tools.ant.Target.performTasks(Target.java:470)
>      [java] 	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1388)
>      [java] 	at org.apache.tools.ant.Project.executeTarget(Project.java:1361)
>      [java] 	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
>      [java] 	at org.apache.tools.ant.Project.executeTargets(Project.java:1251)
>      [java] 	at org.apache.tools.ant.Main.runBuild(Main.java:834)
>      [java] 	at org.apache.tools.ant.Main.startAnt(Main.java:223)
>      [java] 	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
>      [java] 	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
>      [java] Caused by: java.lang.IllegalAccessException: Class org.apache.tools.ant.taskdefs.ExecuteJava can not access a member of class Yylex with modifiers "public static"
>      [java] 	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
>      [java] 	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
>      [java] 	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
>      [java] 	at java.lang.reflect.Method.invoke(Method.java:491)
>      [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.run(ExecuteJava.java:218)
>      [java] 	at org.apache.tools.ant.taskdefs.ExecuteJava.execute(ExecuteJava.java:155)
>      [java] 	... 21 more
>      [java] Java Result: -1
>

**Comment by lsf37** [comment]
Should have another look at the ant test before the 1.8.0 release.

**Comment by lsf37** [comment]
The problem is that the class Yylex isn't public. Will add.
