### ISSUE TITLE
Bazel and Maven have different working directories

### ISSUE THREAD

**Issue by regisd** [jflex-de/jflex#449]
* Maven working directory is where the `pom.xml` is
* Bazel working directory is the sandboxed *runfiles* directory (which corresponds to the root WORKSPACE).

As a result opening files in test differs.

**Comment by regisd** [comment]
Also, quoting @lsf37 and initial reply:
 
> PR #384 makes the release not buildable. The examples now refer to a directory that doesn't exist in the release package.
> We'd either have to do a lot of rewriting in the release process

I'd rather not. With unfrequent releases, this means the release process will always be broken when you try it.

> or change the directory structure for the release. We could do that, but we should be careful not to make it too hard for distribution packaging maintainers to build their packages. The purpose of current structure is to make it obvious what is code, binary, and documentation. Ideally these work independently and in completely separate parts of a directory structure, i.e. doc can be either left out or be put into any part of the file system, which linux distributions like to do.

> In general, the examples should show people how to build things as if they had installed jflex somewhere separately and they are now working in their own build tree. This means referencing other parts of the repo in the examples is always going to be problematic.

Right, I also realise that PR #384 is overly complex.

Adjusting the path is as simple as preprending the bazel package when running bazel, i.e. when `new File(".").getAbsoluteFile().getParentFile()` is `__main__`.

**Comment by regisd** [comment]
So for our tests, I propose to use a helper class, and I have a simpler one in commit 0ae75f2f1e8f517b7472bd7cee0df22e46143842.

For the examples, we could duplicate this class in the `examples/common` directory, or use a short snippet.

```
  private static final String SRC_DIR;	
  static {	
    if ("__main__".equals(new File(".").getAbsoluteFile().getParentFile().getName())) {	
      SRC_DIR = "jflex/examples/simple/src";	
    } else {	
      SRC_DIR = "src";	
    }	
  }
```

**Comment by regisd** [comment]
Concerning the content of the targz, this is quite a different topic, and I didn't realise until now it contained source code.

I think that's unnecessary complexity.

In my view, the use-cases are:

- use jflex in the command line, play with the examples → jflex.tar.gz 
- use in an ant-based project → jflex.tar.gz or jflex-full.jar
- use in a Maven-based project → read the doc online and add a dep in their pom to use jflex-maven-plugin 
-  use in a bazel-based project → read the doc and use bazel rule
- use in a gradle-based project → use third-party gradle plugin
- want to contribute or compile from source → clone the git repo and builds with Maven/Bazel

See also https://github.com/jflex-de/jflex/wiki/Migration-to-Bazel

**Comment by regisd** [comment]
I don't think there are issues any more.

**Comment by lsf37** [comment]
Yes, although I do disagree with the sources-in-targz. I don't think it makes sense to have an official tar.gz release for an open source project without source. But I'm sure we can solve those issues.
