### ISSUE TITLE
Windows: Error on 'git clone'

### ISSUE THREAD

**Issue by archfrog** [jflex-de/jflex#535]
Hi,

I am encountering an issue when cloning the [jflex](https://github.com/jflex-de/jflex) repository.  Git for Windows reports:

```bash
error: unable to create file testsuite/testcases/src/test/cases/filename/filename\u000AFILE_NAMES_MUST_BE_ESCAPED\u000A.flex: No such file or directory
```
The problem is obviously that Windows interprets `\` as a path separator, not as an escape character.

I don't know if it is possible to redo the test case in question so that the bogus file is generated dynamically on the fly?

For now, I use these two commands to get hold of the `jflex` source code:

```bash
git clone -q --no-checkout https://github.com/jflex-de/jflex
git checkout -q -f HEAD
```

If I use the standard `git clone -q https://github.com/jflex-de/jflex` command, Git aborts before checking out the repository locally.

Cheers,
Archfrog

**Comment by regisd** [comment]
Yes, my mistake, this file was added in #399.
I think we can keep a unit test and forget about the integration test.
