### ISSUE TITLE
Lexer has negative yychar when processing files larger than 2 GiB

### ISSUE THREAD

**Issue by vladak** [jflex-de/jflex#536]
The `yychar` variable that holds file offset is `int`, therefore limiting the length of files to 2 GiB - 1. We bumped into this in https://github.com/oracle/opengrok/issues/2560

**Comment by regisd** [comment]
Thanks for the investigation. If I understand correctly, the fix is as easy as changing this from `int` to `long`.

**Comment by vladak** [comment]
I think so. Comprehensive test should be written to make sure any other
offset carrying variables are covered.

po 17. 12. 2018 14:56 odesílatel Régis Décamps <notifications@github.com>
napsal:

**Comment by sarowe** [comment]
PR #558 fixes this problem.

> Comprehensive test should be written to make sure any other offset carrying variables are covered.

I included a test with a compressed file >2GiB.  But I did not extend this fix to any other offset carrying variables; yycolumn and yyline remain ints.

**Comment by regisd** [comment]
I have a bazel test that reproduces

> 1) consumeLargeInput(jflex.testcase.large_input.LargeInputTest)
> java.lang.NegativeArraySizeException
> 	at jflex.testcase.large_input.LargeInputScanner.zzRefill(LargeInputScanner.java:288)
> 	at jflex.testcase.large_input.LargeInputScanner.yylex(LargeInputScanner.java:601)
> 	at jflex.testcase.large_input.LargeInputTest.consumeLargeInput(LargeInputTest.java:22)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> ...

It doesn't come with the 2GB file input from #558 test case. I'll cherry-pick the change by @sarowe to offer a fox that doesn't blow git.

**Comment by regisd** [comment]
Actually `NegativeArraySizeException` is a different bug. It's when we try to `zzrefill()` with an array whose size is an overflow. I don't think we can fix that easily, and the test was actually using a lot of RAM as well.
For the test, the scanner can just test its internal state, as in commit c838d6c2f4a0ffe0b8e2bd7775148846f37d4799
