### ISSUE TITLE
Negative look-ahead inside RegExp

### ISSUE THREAD

**Issue by halirutan** [jflex-de/jflex#553]
This is not a bug report. Rather I'm asking for some ideas/assistance. I'm aware that there was already a [similar issue](https://github.com/jflex-de/jflex/issues/181) but mine is a bit different.
The lexical rules for numbers in the Wolfram Language (Mathematica) are a pain because they combine numbers of different bases, precision, accuracy and further short-forms. I have posted a very detailed explanation [in this SO question](https://stackoverflow.com/questions/54905084/jflex-negative-look-ahead-inside-regex) but in essence my problem is simple:

I match the whole sh&tshow of numbers by combining macros and regexes but inside this large expression, there can be numbers like `1.` or `1.0` on different places. The problem is that Mathematica tokenizes something like `1..` as the number `1` and the operator `..`
That's bad and I cannot get JFlex to do it without the negative look-ahead `(?!regex)`. I'm far away from being experienced with regex and JFlex, but I always found a solution to ugly corner-cases.
I prepared a complete example with test-numbers on [regex101.com](https://regex101.com/r/I47A1I/1). 

Can someone give me a tip or simply say that I'm out of luck here?

**Comment by lsf37** [comment]
If you can have `1.` as a number and `.1` as a number, and want to match multiple of these, but not match `1..1` as the two tokens `1.`, `.1`, then I don't see a good solution apart from doing that in the parser like I suggested in the SO answer.

You might still be able to cook something up with matching each kind of number separately, i.e. something along these lines:

```jflex
Digits = [0-9]+
Number1 = {Digits}((\.){Digits})? | \.{Digits}
Number2 = {Digits}\.
ScientificInteger = {Number} "\*^"(-?){Digits}

{ScientificInteger} |
{Number1} |
{Number2} / [^.]          { return WLElementTypes.NUMBER; }

".."                      { return OPERATOR; }         
```
but if it gets more complex, it'll be pretty error-prone.
