### ISSUE TITLE
Support other output languages (Swift, Objective-C) feasible ?

### ISSUE THREAD

**Issue by hannesoid** [jflex-de/jflex#561]
I've used it in the past with success and was wondering:

Do you think it is worth to consider generating other output languages than Java?

I mostly work with Objective-C and swift, and wondering if this project is based on a templating, that would allow to use syntax of a different language when generating the lexer.
I would assume the generated components like functions, constants, switches, string/character accessing should be available in other than java standard libraries.

**Comment by lsf37** [comment]
It'd probably be possible to do that, but it would be too much maintenance overhead -- we're barely keeping up as it is at the moment. There are also a few assumptions in the spec language as well as the implementation that target Java specifically, so it'd be more than just adding new templates and emitter code.

**Comment by hannesoid** [comment]
makes sense, thanks for looking into it!
