### ISSUE TITLE
Hi,Can you help me generate a Html?

### ISSUE THREAD

**Issue by shixin423** [jflex-de/jflex#564]

**Comment by sarowe** [comment]
Without more context (an Html from what? for what purpose?), we can't really help.

**Comment by shixin423** [comment]
I want to write an Html editor that needs to be highlighted but will not operate.

**Comment by sarowe** [comment]
Maybe you can get some inspiration from the jSyntaxPane project : https://github.com/nordfalk/jsyntaxpane , in particular the XHTML grammar: https://github.com/nordfalk/jsyntaxpane/blob/master/jsyntaxpane/src/main/jflex/jsyntaxpane/lexers/xhtml.flex (note that there are several other languages supported; look in the same folder for others).

See more JFlex grammars linked here: https://github.com/jflex-de/jflex/wiki/External-JFlex-Grammars

**Comment by shixin423** [comment]
I won't operate, but thank you.
