### ISSUE TITLE
Could not find artifact de.jflex:cup:jar:11b in central

### ISSUE THREAD

**Issue by kichel98** [jflex-de/jflex#701]
Hi, I'm trying to configure my first project with JFlex and CUP using Maven. For testing and learning purposes, I wanted to run project which uses cup-maven-plugin (path: jflex/cup/sample-project/), but after:
`mvn install`, I get an error:

`Execution default of goal de.jflex:cup-maven-plugin:1.0:generate failed: Plugin de.jflex:cup-maven-plugin:1.0 or one of its dependencies could not be resolved: Could not find artifact de.jflex:cup:jar:11b in central (https://repo.maven.apache.org/maven2)`. 

Maven logs that it tries to download POM from URL: https://repo.maven.apache.org/maven2/de/jflex/cup/11b/cup-11b.pom, which gives 404 Not Found.

Is there any way to fix it locally or it is an issue connected with deployment?
I would appreciate your help.

**Comment by regisd** [comment]
We provide the cup POM in https://github.com/jflex-de/jflex/tree/master/cup

If you want to use jflex-1.7.0 in a project, see https://github.com/jflex-de/jflex/tree/v1.7.0#usage-with-maven and https://github.com/jflex-de/jflex/tree/v1.7.0/jflex/examples

If you want to use jflex-1.8.0-SNAPSHOT and compile from source, see https://github.com/jflex-de/jflex#build-from-source
