### ISSUE TITLE
mvn compile error

### ISSUE THREAD

**Issue by manojCS98** [jflex-de/jflex#712]
Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.5.1:compile (default-compile) on project MLP189: Compilation failure: Compilation failure:
**[ERROR] Source option 5 is no longer supported. Use 7 or later.
[ERROR] Source option 5 is no longer supported. Use 7 or later.**

**Comment by lsf37** [comment]
Hi @manojCS98, thanks for reporting this. Could you please add for which version of jflex this occurs, and what you were trying to do? (compile a jflex release from source?).

Generally changing source and target to JDK 1.7 might work even for older versions of jflex.

**Comment by regisd** [comment]
Closed because OP didn't provide details.
Also, jflex 1.8.0 has been released and compiles on recent SDK.
