### ISSUE TITLE
set correct JFlex bootstrap version in bazel rule 

### ISSUE THREAD

**Issue by lsf37** [jflex-de/jflex#730]
The skeleton format changed between JFlex 1.7.0 and 1.8.0.

The bazel build is still on 1.7.0, while the mvn build is on 1.8.0 for bootstrapping, which means we still need to maintain the old `skeleton.nested` file from 1.7.0.

@regisd do you have any tips on how to set up bazel to use 1.8.0?

**Comment by regisd** [comment]
Of course, let me send you a PR.

**Comment by regisd** [comment]
I  have published the ruleas https://github.com/jflex-de/bazel_rules/releases/tag/v9
