### ISSUE TITLE
use SPDX license identifiers and make JFlex "REUSE" compliant

### ISSUE THREAD

**Issue by lsf37** [jflex-de/jflex#742]
[SPDX](https://spdx.org) is a good way to keep track of which licenses are being used in a project and I think it would make sense to use them consistently in JFLex -- for ourselves, but also to enable others to check licenses automatically. @regisd has already started using them in new parts of the repo, and I think that's great, we should do that everywhere.

More concretely, I'd propose:
 * for files that we wrote and own the copyright on, *replace* most of the copyright header with:
   * one or more copyright lines (authors)
   * one `SPDX-License-Identifier` line
   * this would remove the `VERSION` comment on java files, but we have that in javadoc almost everywhere now, so removing it removes duplication 
 * for 3rd-party files, *leave* the copyright header *as is*, but add an `SPDX-License-Identifier` line as a separate comment.
 * for all files that are not commentable, use a `dep5` file that lists license and copyright
 * review our own documentation files and put those under CC-BY-SA-4.0 if we haven't already done so
 * use `resue lint` (see http://github.com/reuse-tool) to check coverage
 * include `reuse lint` in CI

**Comment by lsf37** [comment]
@regisd, @sarowe would you be happy for me to go ahead with this?

**Comment by sarowe** [comment]
+1 LGTM

**Comment by regisd** [comment]
+1 Sure

**Comment by lsf37** [comment]
Cool, will go ahead with this.
