### ISSUE TITLE
%eof{ ... %eof} is not being included when trying to upgrade to v1.8.1 from 1.7.0

### ISSUE THREAD

**Issue by idodeclare** [jflex-de/jflex#743]
Hello,

After trying an upgrade of OpenGrok to JFlex v1.8.1, I found that code specified in `%eof{` is not included anymore in the generated lexers. I browsed through the JFlex manual, but I didn't see anything to indicate the handling would have changed.

(I did check but didn't see any other `%eof` open issues here.)

Please any advice?

Thank you.

**Comment by lsf37** [comment]
That sounds like a bug. I'll investigate.

**Comment by lsf37** [comment]
Ok, this reproduces easily and is indeed a bug. It looks like `%eofthrow` might also be affected.

**Comment by lsf37** [comment]
It looks like it was introduced in 3e570d95e2b4c4d3cdb33eb6be30d3e95fbcdeb8 and happens when `%eofclose` is not present. Apparently our tests always had this, so the regression slipped through.

**Comment by lsf37** [comment]
Ok, the fix is working. I should clean this up a little more and wanted to do another few small things that would fit into an 1.8.2 release. 

Are you blocked on this, or can it wait another 2-3 weeks?

**Comment by idodeclare** [comment]
Thank you for investigating, @lsf37 . We’re not blocked and can await a release.

**Comment by lsf37** [comment]
Perfect, that'll make a 1.8.2 release a bit more meaningful.

**Comment by regisd** [comment]
Sorry for the regression. PR #501 was supposed to be a simple refactoring.

**Comment by idodeclare** [comment]
Thank you, @regisd . No big trouble.

**Comment by idodeclare** [comment]
Hello. Might we be getting a bugfix soon?

**Comment by lsf37** [comment]
Sorry, big work deadline got in the way. I'll see how far I get today with a release.

**Comment by idodeclare** [comment]
Many thanks.
—CF

**Comment by lsf37** [comment]
Version 1.8.2 is now out!

**Comment by idodeclare** [comment]
Thank you, @lsf37 !

**Comment by lsf37** [comment]
No worries, sorry that it too so long.
