### ISSUE TITLE
%eof not work

### ISSUE THREAD

**Issue by vietanhtwdk** [jflex-de/jflex#757]
I tried to use 
%eof{
	...
%eof}
but it does nothing, i can't find method void yy_do_eof() in java file too.
%eofval work normally

**Comment by vietanhtwdk** [comment]
I'm down to version 1.7.0 and %eof work, im using jdk 11

**Comment by lsf37** [comment]
Yes, this bug was introduced in 1.8.0, and is fixed in the development version (see #743). I'm hoping to get a release out in the next few days to make the fix available.
