### ISSUE TITLE
NPE occurs when generating dot file of an NFA

### ISSUE THREAD

**Issue by Mivik** [jflex-de/jflex#769]
I chose exactly the lexer in `examples/simple` and appended "-dot" argument. Then the following NPE occurred: 
```
../../bin/jflex -d out/genfiles -dot src/main/jflex/simple.flex
Reading "src/main/jflex/simple.flex"
Constructing NFA : 
Unexpected exception encountered. This indicates a bug in JFlex.
Please consider filing an issue at http://github.com/jflex-de/jflex/issues/new

java.lang.NullPointerException
	at jflex.core.NFA.dotFormat(NFA.java:502)
	at jflex.core.NFA.writeDot(NFA.java:478)
	at jflex.generator.LexGenerator.generate(LexGenerator.java:80)
	at jflex.Main.generate(Main.java:320)
	at jflex.Main.main(Main.java:336)
```

**[It](https://github.com/jflex-de/jflex/blob/master/jflex/src/main/java/jflex/core/NFA.java#L502)** seems that you didn't notice that the StateSet in table can be null while generating the graph.

**Comment by lsf37** [comment]
Thanks for the report. Yes, you're right, it can be `null` and will in fact often be `null`. At least it should be easy to fix.

**Comment by regisd** [comment]
This issue should be easy to fix, either with a null-check, or using `Optional`.
