### ISSUE TITLE
A tiny error in simple.flex

### ISSUE THREAD

**Issue by Mivik** [jflex-de/jflex#770]
[Here](https://github.com/jflex-de/jflex/blob/master/jflex/src/test/resources/jflex/simple.flex#L22)

We should use 
```flex
STRING_TEXT=(\\\"|[^\n\r\"\\]|\\{WHITE_SPACE_CHAR}+\\)*
```
instead of
```flex
STRING_TEXT=(\\\"|[^\n\r\"]|\\{WHITE_SPACE_CHAR}+\\)*
```
since the original one can match a single backslash, which means "\\" (a backslash surrounded by two quotes) will be recognized as a string, which is not expected.

**Comment by lsf37** [comment]
Agreed, the example would be better without.

Maybe the whole example should be redone, it's based on some very old code and is strongly reduced from that original, so there are probably a few more bits that don't really make sense, which is not so good for people trying to understand things.

**Comment by Mivik** [comment]
> Agreed, the example would be better without.
> 
> Maybe the whole example should be redone, it's based on some very old code and is strongly reduced from that original, so there are probably a few more bits that don't really make sense, which is not so good for people trying to understand things.

Well I discovered this mistake while I was trying to implement this simple lexer in my own way, and my lexer generator threw an error telling me that there's a conflict since "\" can be both recognized as a unclosed string and a standard string. But when generating the lexer with jflex I didn't notice any error or warning. IMHO, jflex should emit a warning in these cases instead of accepting it silently. And due to my poor understanding of lexer, pointing out my improper opinion is much appreciated.

**Comment by lsf37** [comment]
> Well I discovered this mistake while I was trying to implement this simple lexer in my own way, and my lexer generator threw an error telling me that there's a conflict since "\" can be both recognized as a unclosed string and a standard string. But when generating the lexer with jflex I didn't notice any error or warning. IMHO, jflex should emit a warning in these cases instead of accepting it silently. And due to my poor understanding of lexer, pointing out my improper opinion is much appreciated.

I don't think jflex should warn here, not all languages have `\` as an escape character for strings, and without further context the `"\"` is just the string containing `\` in this lexer, which might be perfectly fine. But it's not exactly a common scenario, so it's not good for the example.

**Comment by Mivik** [comment]
> > Well I discovered this mistake while I was trying to implement this simple lexer in my own way, and my lexer generator threw an error telling me that there's a conflict since "" can be both recognized as a unclosed string and a standard string. But when generating the lexer with jflex I didn't notice any error or warning. IMHO, jflex should emit a warning in these cases instead of accepting it silently. And due to my poor understanding of lexer, pointing out my improper opinion is much appreciated.
> 
> I don't think jflex should warn here, not all languages have `\` as an escape character for strings, and without further context the `"\"` is just the string containing `\` in this lexer, which might be perfectly fine. But it's not exactly a common scenario, so it's not good for the example.

Pardon me for my unclear description. I said "jflex should emit a warning in these cases", where "these cases" actually means when a specific content can be recognized as two different tokens (or trigger two different actions) at the same time, in another word, when an conflict is found in the lexer rule.

**Comment by lsf37** [comment]
> where "these cases" actually means when a specific content can be recognized as two different tokens (or trigger two different actions) at the same time, in another word, when an conflict is found in the lexer rule.

Ok, I understand now. This is a problem that doesn't happen in JFlex, the semantics of how lexical rules are interpreted always produce a unique result, i.e. there are no conflicts. You can get such conflicts for instance in LR parsers where you then have to tell the tool how to resolve the conflict (or it picks a default and emits a warning).

**Comment by regisd** [comment]
Hey @Mivik. I'm happy to accept a pull request that updates the example for a simpler one.

**Comment by lsf37** [comment]
Thanks for providing the fix!
