### ISSUE TITLE
Why does Unicode_2_1.java Age=2.0 not have all intervals?

### ISSUE THREAD

**Issue by regisd** [jflex-de/jflex#833]
While re-generating the Unicode data with the ucd_generator (#831), I had an unexpected output with Unicode 2.1.1

In both **Age=2.0** and **Age=2.1**, I have
```
        + "\ufffd\uffff"
        + "\ud83f\udffe\ud83f\udfff"
        + "\ud87f\udffe\ud87f\udfff"
        + "\ud8bf\udffe\ud8bf\udfff"
        + "\ud8ff\udffe\ud8ff\udfff"
        + "\ud93f\udffe\ud93f\udfff"
        + "\ud97f\udffe\ud97f\udfff"
        + "\ud9bf\udffe\ud9bf\udfff"
        + "\ud9ff\udffe\ud9ff\udfff"
        + "\uda3f\udffe\uda3f\udfff"
        + "\uda7f\udffe\uda7f\udfff"
        + "\udabf\udffe\udabf\udfff"
        + "\udaff\udffe\udaff\udfff"
        + "\udb3f\udffe\udb3f\udfff"
        + "\udb7f\udffe\udbff\udfff",
``` 

whereas the current version of Unicode_2_1.java doesn't. [L746](https://github.com/jflex-de/jflex/blob/master/jflex/src/main/java/jflex/core/unicode/data/Unicode_2_1.java#L746)

**Comment by sarowe** [comment]
The maximum code point in Unicode 2.1 (and 2.0) is U+FFFF :
https://github.com/jflex-de/jflex/blob/master/jflex/src/main/java/jflex/core/unicode/data/Unicode_2_1.java#L6

**Comment by regisd** [comment]
Cheers, this is indeed caused, this was caused by the DerivedAgeScanner whose data comes from UNIDATA.
