### ISSUE TITLE
Help: ComplexSymbolFactory example

### ISSUE THREAD

**Issue by chuck2098** [jflex-de/jflex#894]
Hi,
Is there an example of ComplexSymbolFactory usage?
I tried to see on http://www2.cs.tum.edu/projects/cup/docs.php#advanced-symbols but I don't understand well how I can use it.
Can Anyone help me?

Thanks

**Comment by regisd** [comment]
As you pointed, `ComplexSymbolFactory` is part of cup2, not jflex.

We do however have a few example usage of cup in our examples ; and IIIRC we have been avoiding this class. Have you seen #384 ?
