### ISSUE TITLE
java cup runtime

### ISSUE THREAD

**Issue by Shelby69** [jflex-de/jflex#911]
![WhatsApp Image 2021-04-07 at 21 27 41](https://user-images.githubusercontent.com/63015549/113959671-e67b9e00-97e8-11eb-810a-5e33de746b28.jpeg)

Estoy tratando de hacer el ejemplo del Manual, página 12-13 y tengo este problema con CUP

**Comment by regisd** [comment]
"java cup runtime" what is the bug about.
