### ISSUE TITLE
Could not get resource 'https://jetbrains.bintray.com/intellij-third-party-dependencies/org/jetbrains/intellij/deps/jflex/jflex/1.7.0-1/jflex-1.7.0-1.pom'.

### ISSUE THREAD

**Issue by jnorthrup** [jflex-de/jflex#938]
> Could not resolve org.jetbrains.intellij.deps.jflex:jflex:1.7.0-1.
            > Could not get resource 'https://jetbrains.bintray.com/intellij-third-party-dependencies/org/jetbrains/intellij/deps/jflex/jflex/1.7.0-1/jflex-1.7.0-1.pom'.

@Dmitry @Dmitriy-Panov
 https://blog.jetbrains.com/idea/2021/04/migration-from-bintray/#remark42__comment-57d7d368-7d0b-44a6-b9ec-53053f7a9ca9 seems to be slightly shallow on repairing older usages in gradle

**Comment by lsf37** [comment]
I don't think this has anything to do with jflex as such, it looks like a problem in how intellij/bintray handles dependencies. 

If you disagree, please re-open.
