### ISSUE TITLE
Unexpected exception encountered. Not normalised type = CHAR

### ISSUE THREAD

**Issue by AidanSmiley** [jflex-de/jflex#939]
Hello.
I'm in the process of making a scanner for my Compiler Design class using JFlex and Cup and ran into this error. Not 100% sure if it's from my own code or something else and figured I'd report the bug anyway. Attached is the output after attempting to compile as well as a link to a repo of my current project that should reproduce the bug.

Any help at all would be appreciated thank you.

https://github.com/AidanSmiley/CompilerProjectP1/tree/main

![image](https://user-images.githubusercontent.com/43795046/135954969-039488e9-c14f-4bad-a472-7cb8e96eca96.png)

**Comment by lsf37** [comment]
This does look like an actual jflex bug. Thanks for reporting it, I'll take a closer look in the next few days.
