### ISSUE TITLE
generated-class.md missing from manual published on website

### ISSUE THREAD

**Issue by kkofler** [jflex-de/jflex#968]
The manual on the website, in both formats:
* https://jflex.de/manual.html
* https://jflex.de/manual.pdf

is missing this section:
https://github.com/jflex-de/jflex/blob/master/docs/md/generated-class.md
that was split from `lex-specs.md` in commit e343125fde88c5d5df2a7d6757c6ccb07d8f67a7.

In particular, this means that methods such as `yypushback` are not documented anywhere in the manual.

**Comment by lsf37** [comment]
Oh, wow, that's very unfortunate. Well spotted, thanks for that.

**Comment by lsf37** [comment]
Reopening, because the updated manual still needs to go on the website.

**Comment by lsf37** [comment]
Now done, the website should show the manual with the section included and the next jflex release will ship with the full manual again.

**Comment by kkofler** [comment]
Wow, that was quick, thanks!
